# See the examples folder for a full scientifc Python environment
channels:
  - conda-forge

dependencies:
  # HUB BASICS. ALWAYS INCLUDE
  - jupyter_contrib_nbextensions==0.5.1
  # Required until https://github.com/jupyterhub/repo2docker/pull/1196 is merged
  - jupyterhub-singleuser>=3.0,<4.0
  # Set default python version to 3.10 - repo2docker sets it to 3.7 instead by default,
  # which can limit us to older package versions
  - python=3.10

  # Now add your extra packages here
