channels:
  - conda-forge
dependencies:
  # dupe repo2docker constraints # TODO avoid?
  # https://github.com/jupyterhub/repo2docker/blob/HEAD/repo2docker/buildpacks/conda/environment.yml
  - python=3.10
  - jupyter-resource-usage=1.*
  - jupyterhub-singleuser=5.*
  - notebook=6.*
  ## Core scientific python stack
  - dask[array,distributed]
  - dask-image
  - dask-geopandas
  - flox>=0.7.2,<1.0.0
  - networkx
  - numba
  - numpy<2.0
  - pandas
  - scikit-image
  - scikit-learn
  - scipy
  - statsmodels
  - xarray
  - xarray-datatree==0.0.6
  ## echopype
  - echopype
  ## Core visualization packages
  - bokeh
  - cartopy
  - cmocean
  - geoviews
  - holoviews
  - hvplot
  - ipyleaflet
  - ipympl
  - matplotlib
  - python-graphviz
  - seaborn
  ## Other science packages
  # Geospatial
  - geopandas
  - rasterio
  - rioxarray
  - geopy
  # Other science packages
  - pvlib
  - jinja2
  - psutil>=5.9.1
  - requests
  - bottleneck
  - pytz
  - aiohttp
  - pynmea2
  ## File formats and file management, download, dataset caching
  - awscli
  - earthaccess
  - h5netcdf
  - netCDF4>1.6
  - kerchunk
  - pillow
  - zarr
  - s3fs
  - fsspec
  # gh-scoped-creds allows users to securely push to GitHub from their repo.
  # https://blog.jupyter.org/securely-pushing-to-github-from-a-jupyterhub-3ee42dfdc54f has
  # some more information
  - gh-scoped-creds
  ## JupyterLab extensions and helpers
  - bash_kernel
  - dask-labextension
  - ipykernel
  - jupyterlab-geojson
  - jupyterlab-git
  - jupyterlab-h5web
  - jupyter-book
  - jupytext
  - tqdm
  ## VS Code support
  - jupyter-vscode-proxy
  - code-server>4.0
